import type { Category } from '../types';

export const defaultCategories: Category[] = [
  {
    id: 'food',
    name: 'Alimentación',
    icon: '🍔',
    type: 'expense',
    subcategories: [
      { id: 'breakfast', name: 'Desayuno' },
      { id: 'lunch', name: 'Almuerzo' },
      { id: 'dinner', name: 'Cena' },
      { id: 'delivery', name: 'Delivery' },
      { id: 'snacks', name: 'Snacks' },
      { id: 'restaurants', name: 'Restaurantes' },
      { id: 'coffee', name: 'Café' },
      { id: 'food-other', name: 'Otros' },
    ],
  },
  {
    id: 'transport',
    name: 'Transporte',
    icon: '🚗',
    type: 'expense',
    subcategories: [
      { id: 'fuel', name: 'Combustible' },
      { id: 'taxi', name: 'Taxi' },
      { id: 'uber', name: 'Uber' },
      { id: 'maintenance', name: 'Mantenimiento' },
      { id: 'tolls', name: 'Peajes' },
      { id: 'public-transport', name: 'Transporte público' },
      { id: 'transport-other', name: 'Otros' },
    ],
  },
  {
    id: 'shopping',
    name: 'Compras',
    icon: '🛒',
    type: 'expense',
    subcategories: [
      { id: 'clothing', name: 'Ropa' },
      { id: 'tech', name: 'Tecnología' },
      { id: 'home-items', name: 'Hogar' },
      { id: 'accessories', name: 'Accesorios' },
      { id: 'online-shopping', name: 'Compras online' },
      { id: 'shopping-other', name: 'Otros' },
    ],
  },
  {
    id: 'entertainment',
    name: 'Entretenimiento',
    icon: '🎮',
    type: 'expense',
    subcategories: [
      { id: 'cinema', name: 'Cine' },
      { id: 'games', name: 'Juegos' },
      { id: 'subscriptions', name: 'Suscripciones' },
      { id: 'outings', name: 'Salidas' },
      { id: 'travel', name: 'Viajes' },
      { id: 'events', name: 'Eventos' },
      { id: 'entertainment-other', name: 'Otros' },
    ],
  },
  {
    id: 'home',
    name: 'Hogar',
    icon: '🏠',
    type: 'expense',
    subcategories: [
      { id: 'rent', name: 'Alquiler' },
      { id: 'electricity', name: 'Luz' },
      { id: 'water', name: 'Agua' },
      { id: 'internet', name: 'Internet' },
      { id: 'home-maintenance', name: 'Mantenimiento' },
      { id: 'home-other', name: 'Otros' },
    ],
  },
  {
    id: 'work',
    name: 'Trabajo / Negocio',
    icon: '💼',
    type: 'expense',
    subcategories: [
      { id: 'advertising', name: 'Publicidad' },
      { id: 'tools', name: 'Herramientas' },
      { id: 'software', name: 'Software' },
      { id: 'work-transport', name: 'Transporte laboral' },
      { id: 'staff', name: 'Personal' },
      { id: 'equipment', name: 'Equipamiento' },
      { id: 'work-other', name: 'Otros' },
    ],
  },
  {
    id: 'personal',
    name: 'Personal',
    icon: '❤️',
    type: 'expense',
    subcategories: [
      { id: 'health', name: 'Salud' },
      { id: 'education', name: 'Educación' },
      { id: 'self-care', name: 'Cuidado personal' },
      { id: 'personal-clothing', name: 'Ropa' },
      { id: 'personal-other', name: 'Otros' },
    ],
  },
  {
    id: 'debts-cat',
    name: 'Deudas',
    icon: '💳',
    type: 'expense',
    subcategories: [
      { id: 'credit-card-payment', name: 'Tarjeta de crédito' },
      { id: 'loans', name: 'Préstamos' },
      { id: 'installments', name: 'Cuotas' },
      { id: 'interest', name: 'Intereses' },
    ],
  },
  {
    id: 'investments-cat',
    name: 'Inversiones',
    icon: '📈',
    type: 'both',
    subcategories: [
      { id: 'stocks', name: 'Acciones' },
      { id: 'funds', name: 'Fondos' },
      { id: 'crypto', name: 'Criptomonedas' },
      { id: 'real-estate', name: 'Bienes raíces' },
      { id: 'investments-other', name: 'Otros' },
    ],
  },
  {
    id: 'savings-cat',
    name: 'Ahorro',
    icon: '💰',
    type: 'both',
    subcategories: [
      { id: 'emergency-fund', name: 'Fondo de emergencia' },
      { id: 'savings-goal', name: 'Meta de ahorro' },
      { id: 'general-savings', name: 'Ahorro general' },
    ],
  },
  {
    id: 'salary',
    name: 'Sueldo',
    icon: '💵',
    type: 'income',
    subcategories: [{ id: 'monthly-salary', name: 'Sueldo mensual' }],
  },
  {
    id: 'commissions',
    name: 'Comisiones',
    icon: '📊',
    type: 'income',
    subcategories: [{ id: 'sales-commission', name: 'Comisión de ventas' }],
  },
  {
    id: 'business-income',
    name: 'Negocio',
    icon: '🏢',
    type: 'income',
    subcategories: [
      { id: 'business-sales', name: 'Ventas' },
      { id: 'business-services', name: 'Servicios' },
    ],
  },
  {
    id: 'freelance',
    name: 'Trabajos adicionales',
    icon: '🔧',
    type: 'income',
    subcategories: [
      { id: 'freelance-work', name: 'Freelance' },
      { id: 'side-jobs', name: 'Trabajos eventuales' },
    ],
  },
  {
    id: 'rental-income',
    name: 'Alquileres',
    icon: '🏘️',
    type: 'income',
    subcategories: [{ id: 'property-rental', name: 'Alquiler de propiedad' }],
  },
  {
    id: 'other-income',
    name: 'Otros ingresos',
    icon: '💸',
    type: 'income',
    subcategories: [
      { id: 'gifts', name: 'Regalos' },
      { id: 'refunds', name: 'Devoluciones' },
      { id: 'misc-income', name: 'Otros' },
    ],
  },
];
